apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
  namespace: jenkins
  labels:
    some-label: jenkins-pipeline
  annotations:  # Agrega esta sección para incluir la anotación
    kubernetes.io/config.mirror: jenkins-agent-mirror
spec:
  containers:
  - name: jenkins-agent
    image: 309682544380.dkr.ecr.us-east-1.amazonaws.com/jenkins-agent:latest
    command:
    - cat
    tty: true
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: "1"
        memory: 1024Mi