apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent
  namespace: jenkins
  labels:
    agent-name: jenkins-pipeline
spec:
  serviceAccountName: jenkins-agent
  securityContext:
    runAsUser: 0
    fsGroup: 0
    runAsNonRoot: false
  containers:
  - name: dind
    image: docker:dind
    command:
    - cat
    tty: true
    securityContext:
      privileged: true
    volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker-socket
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock