apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-card-simulator
  labels:
    app: credit-card-simulator
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: credit-card-simulator
  template:
    metadata:
      labels:
        app: credit-card-simulator
    spec:
      containers:
        - name: credit-card-simulator
          image: 309682544380.dkr.ecr.us-east-1.amazonaws.com/credit-card-simulator:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  selector:
    app: credit-card-simulator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
